version: '3.8'

services:
  web:
    image: todo-api
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - DB_SERVER
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "${DB_PASSWORD}"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - 1433:1433
    volumes:
      - mssql_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  mssql_data:
